### PR TITLE
Update play, sbt versions

### PR DESCRIPTION
**Pull request by joprice**

### CODE REVIEW

**Comment by mchv** [comment]
Thanks for the pull request!
Do you know if it is possible to easily keep `/tmp` path for publishing with `build.sbt` file?

**Comment by joprice** [comment]
Not sure I know what you mean by that?

**Comment by mchv** [comment]
In the current changes, you removed this line:

```
publishTo := Some(Resolver.file("file", file(Option(System.getProperty("repository.path")).getOrElse("/tmp"))))
```

But did not add a similar feature in the `build.sbt` definition.

**Comment by joprice** [comment]
Oops! I'll put it back

**Comment by joprice** [comment]
Updated

**Comment by joprice** [comment]
Closing as this is out of date by now.

**Pull request closed without merging**
